type: repl
verbose: True
max_rounds: 10
reset_state_on_result_fn: False
llm:
  # model_name: gpt-3.5-turbo-0301
  model_name: gpt-4
  max_tokens: 512
  temperature: 0
llm_kwargs:
  stop:
    - ">>>"
    - "```"
prompt_cfg:
  base: base_no_learn
  suffix: suffix
  loop_prevention: loop_prevention
  sentence_similarity_model: "all-mpnet-base-v2"
  custom_prompt_db_file: 2023_12_23_090217d1.prompt_db.json
  prompt_separator: "\n"
  top_k: 16
  db:
    - scenario.*
api:
  include_names:
    - wait_for_trigger
    - get_obj_names
    - get_obj_pos
    - denormalize_xy
    - put_first_on_second
import_lmps:
  fgen: ../../common/fgen