type: simple
max_tokens: 512
temperature: 0
query_prefix: "# "
query_suffix: "."
llm:
  type: ChatOpenAI
  model_name: gpt-3.5-turbo-0301
  max_tokens: 512
  temperature: 0
stop:
  - "# "
  - "objects = ["
maintain_session: true
include_context: true
context_vars:
  objects: get_obj_names
import_lmps:
  fgen: fgen
  parse_position: parse_position
  parse_obj_name: parse_obj_name
