type: simple
max_tokens: 512
temperature: 0
query_prefix: "# "
query_suffix: "."
return_val_name: ret_val
signature:
  parameters:
    - name: natural_language_description
      type: str
  return:
    List[str]
  comment:
    resolve a NL description to a list of object ids
llm:
  type: ChatOpenAI
  model_name: gpt-3.5-turbo-0301
  max_tokens: 512
  temperature: 0
stop:
  - "# "
  - "objects = ["
maintain_session: false
include_context: true
context_vars:
  objects: get_obj_names
api:
  include_all: True
import_lmps:
  fgen: fgen