type: dynamic_cap_lmp
max_tokens: 512
temperature: 0
query_prefix: "# "
query_suffix: "."
return_val_name: ret_val
signature:
  parameters:
    - name: natural_language_description
      type: str
  return:
    List[np.ndarray]
  comment:
    resolve a NL description to a list of 2D points in robot base frame
prompt_cfg:
  base: base_parse_position
  sentence_similarity_model: "all-mpnet-base-v2"
  custom_prompt_db_file: parse_position.dynamic_prompt_db.json
  top_k: 9
  context_prefix_length: 0
  db:
    - parse_position.*
llm:
  type: ChatOpenAI
  model_name: gpt-4-0613
  max_tokens: 512
  temperature: 0
stop:
  - "# "
  - "objects = ["
maintain_session: false
include_context: false
context_vars: []
api:
  include_all: True
import_lmps:
  fgen: ../original/fgen