type: helper
top_k: 16
llm:
  type: ChatOpenAI
  model_name: gpt-4-0613
  max_tokens: 512
  temperature: 0
api:
  include_names:
    - get_obj_names
    - get_obj_pos
    - denormalize_xy
    - put_first_on_second
